--- #YAML:1.0
name:                NEXT-init
version:             1.04.2
abstract:            
DWIM data inheritence for hashes and arrays for 
simple object or ones with mutiple base classes.
Handles sanity checks between class data types,
default construct and init.


license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    NEXT:                          0
    Scalar::Util:                  0
    strict:                        0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
